src/PokemonGOWeb/Models/PokemonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokemonGOWeb.Models
{
    public class PokemonViewModel
    {
    }
}

src/PokemonGOWeb/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace PokemonGOWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/PokemonGOWeb/Controllers/PokemonController.cs
using PokemonGOWeb.Models;
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using DataAcess;
using System.Web.Helpers;

namespace PokemonGOWeb.Controllers
{
    public class PokemonController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        //LIST FUNCTION//
        // get pokemon list using AngularJS and EF
        public JsonResult GetPokeList()
        {
            //creating the DBContext
            PokemonEntities pk;
            pk = new PokemonEntities();
            pk.Configuration.ProxyCreationEnabled = false;//to be able to serialize

            //Pokemon retrieve list
            List<Pokemon> Pokemon = new List<Pokemon>();

            //lambda query
            var query = (from p in pk.Pokemons
                         join t in pk.PokemonTypes
                         on p.PokemonTypeId equals t.Id
                         select new {
                             Id = p.Id,
                             Name = p.Name,
                             ImagePath = p.ImagePath,
                             CurrentHave = p.CurrentHave,
                             PokemonTypeId = p.PokemonTypeId,
                             Description = t.Description
                         }).ToList();

            //Adding the result to the final list
            foreach (var poke in query)
            {
                Pokemon pokeAux = new Pokemon();
                pokeAux.Id = poke.Id;
                pokeAux.ImagePath = poke.ImagePath;
                pokeAux.Name = poke.Name;
                pokeAux.PokemonTypeId = poke.PokemonTypeId;
                pokeAux.CurrentHave = poke.CurrentHave;
                pokeAux.PokemonTypes = poke.Description;
                Pokemon.Add(pokeAux);
            }
            //fetch results
            return new JsonResult { Data = Pokemon, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult GetPokeTypeList()
        {
            //creating the DBContext
            PokemonEntities pk;
            pk = new PokemonEntities();
            pk.Configuration.ProxyCreationEnabled = false;//to be able to serialize

            //Pokemon retrieve list
            List<PokemonType> PokeType = new List<PokemonType>();

            //lambda query
            var query = (from t in pk.PokemonTypes
                         select new
                         {
                             Id = t.Id,
                             Description = t.Description
                         }).ToList();

            //Adding the result to the final list
            foreach (var type in query)
            {
                PokemonType typeAux = new PokemonType();
                typeAux.Id = type.Id;
                typeAux.Description = type.Description;
                PokeType.Add(typeAux);
            }
            //fetch results
            return new JsonResult { Data = PokeType, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //CREATE FUNCTION//
        [HttpPost]
        public ActionResult CreatePokemon(Pokemon pokemon)
        {
            //creating the DBContext
            PokemonEntities pk;
            pk = new PokemonEntities();
            pk.Configuration.ProxyCreationEnabled = false;//to be able to serialize

            //select to check if we will find the register on DB
            Pokemon pokeCreate = new Pokemon();
            //giving atributes values
            pokeCreate.ImagePath = pokemon.ImagePath;
            pokeCreate.Name = pokemon.Name;
            pokeCreate.PokemonTypeId = pokemon.PokemonTypeId;
            //adding to DB
            pk.Pokemons.Add(pokeCreate);
            pk.SaveChanges();

            return View("~/Views/Home/Index.cshtml");
        }

        //UPDATE FUNCTION//
        [HttpPost]
        public JsonResult UpdatePokemon(Pokemon pokemon)
        {
            //creating the DBContext
            PokemonEntities pk;
            pk = new PokemonEntities();
            pk.Configuration.ProxyCreationEnabled = false;//to be able to serialize

            //select to check if we will find the register on DB
            Pokemon pokeUpd = pk.Pokemons.Where(p => p.Id == pokemon.Id).FirstOrDefault();
            if (pokeUpd != null)
            {
                //Here we'll only update the CurrentHave field, but we could update the entire row if it's needed.
                pokeUpd.CurrentHave = !pokeUpd.CurrentHave;
                pk.SaveChanges();
                return new JsonResult { Data = "Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
            else
            {
                return new JsonResult { Data = "Error", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
        //DELETE FUNCTION//
        [HttpPost]
        public JsonResult DeletePokemon(Pokemon pokemon)
        {
            //creating the DBContext
            PokemonEntities pk;
            pk = new PokemonEntities();
            pk.Configuration.ProxyCreationEnabled = false;//to be able to serialize

            //select to check if we will find the register on DB
            Pokemon pokeDel = pk.Pokemons.Where(p => p.Id == pokemon.Id).FirstOrDefault();
            if (pokeDel != null)
            {
                //Here we'll only delete the row.
                pk.Pokemons.Remove(pokeDel);
                pk.SaveChanges();
                return new JsonResult { Data = "Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
            else
            {
                return new JsonResult { Data = "Error", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
    }
}

src/PokemonGOWeb/Controllers/PokemonTypeController.cs
using System.Web.Mvc;

namespace PokemonGOWeb.Controllers
{
    public class PokemonTypeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(string word)
        {
            return View("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Update()
        {
            return View();
        }

        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(int id)
        {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            return View("Index");
        }
    }
}

src/PokemonGOWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>Seja bem-vindo!</h1>
<div ng-controller="HomeController">
    <div>
        <img src="~/Content/images/001.png" />
        <img src="~/Content/images/002.png" />
        <img src="~/Content/images/003.png" />
        <img src="~/Content/images/004.png" />
        <img src="~/Content/images/005.png" />
        <img src="~/Content/images/006.png" />
        <img src="~/Content/images/007.png" />
        <img src="~/Content/images/008.png" />
        <img src="~/Content/images/009.png" />
    </div>
    <p>
        Seu projeto está rodando e você está quase pronto para o desafio Hands On. Verifique abaixo alguns pontos adicionais:
    </p>

    <ul>
        <li>
            Verifique se você tem alguma instância do SQL Server instalada, onde você consiga criar um novo banco de dados.
            A solução será responsável por criar as tabelas iniciais. Você pode testar a conexão antes do desafio, se quiser.
        </li>
        <li>Lembre-se de enviar o seu usuário do bitbucket por e-mail para que você tenha permissão para realizar o desafio.</li>
    </ul>
    <p>
        Você terá liberdade para fazer do seu jeito. Estaremos avaliando a lógica, adequação a arquitetura proposta,
        qualidade de código, performance e boas práticas. Pense que está fazendo algo que será entregue para um cliente.
    </p>
    <p>Boa sorte!</p>
</div>

src/PokemonGOWeb/Views/Pokemon/Create.cshtml
@{
    ViewBag.Title = "Criar Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div ng-controller="PokemonController">
    <h2>Criar Pokémon</h2>
    <form id="pokeForm" name="pokeForm">
        <div class="form-group">
            <label>Nome</label>
            <input name="name" id="name" ng-model="pokeNome" ng-required="true" type="text" class="form-control" placeholder="Inserir o nome">
        </div>
        <div class="form-group">
            <label>Imagem</label>
            <input name="img" id="img" ng-model="pokeImg" ng-required="true" type="text" class="form-control" placeholder="/images/001.png ...">
        </div>

        <div class="form-group">
            <label for="exampleSelect1">Tipo de Pokémon</label>
            <select ng-click="loadType();" class="form-control" id="exampleSelect1" ng-model="selectedType">
                <option value="" selected>Selecione um Tipo...</option>
                <option ng-repeat="type in arrPokemonsTypes" ng-value="type.Id">{{type.Description}}</option>
            </select>
        </div>
        <button ng-click="CreatePokemon();" class="btn btn-primary">Salvar</button>
    </form>
</div>

src/PokemonGOWeb/Views/Pokemon/Delete.cshtml
@{
    ViewBag.Title = "Excluir Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir Pokémon</h2>

<form>
    <div class="form-group">
        <img src="http://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png" class="img-rounded">
    </div>
    <div class="form-group">
        <label>Nome: Pikachu</label>
    </div>
    <div class="form-group">
        <label>Possui Pokémon: Sim</label>
    </div>
    <div class="form-group">
        <label>Tipo de Pokémon: Elétrico</label>
    </div>
    <button type="submit" class="btn btn-primary">Excluir</button>
</form>

src/PokemonGOWeb/Views/Pokemon/Index.cshtml
@{
    ViewBag.Title = "Pokémons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div ng-controller="PokemonController">
    <h2>Pokémons</h2>
    <div class="row">
        <div class="col-lg-3">
            @Html.ActionLink("Criar Pokémon", "Create", "Pokemon", null, new { @class = "btn btn-primary btn-large" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-5">
            <input id="pokeSearch" name="pokeSearch" ng-model="pokeSearch" placeholder="Procure Seu Pokemon por Nome / Tipo..." type="text" class="form-control left">
        </div>
    </div>
    <table class="table table-striped" style="max-height:475px;overflow-y:scroll;">
        <thead>
            <tr>
                <th>#</th>
                <th>Imagem</th>
                <th>Nome</th>
                <th>Tipo</th>
                <th>Capturado</th>
                <th>Excluir</th>
            </tr>
        </thead>
        <tbody>
            <!--Here we are building our table using the ng-repeat to loop the pokemon list-->
            <tr ng-repeat="pokemon in arrPokemons | filter:pokeSearch">
                <td>{{pokemon.Id}}</td>
                <td><img src="~/Content{{pokemon.ImagePath}}" style="max-height: 30px;" /></td>
                <td>{{pokemon.Name}}</td>
                <td>{{pokemon.PokemonTypes}}</td>
                <!--Here we're setting if we have or not the pokemon-->
                <td><span ng-click="updatePokeCheck(pokemon)" ng-class="{'glyphicon glyphicon-check': pokemon.CurrentHave, 'glyphicon glyphicon-unchecked': !pokemon.CurrentHave}" style="cursor:pointer;"></span></td>
                <!--Run the delete function-->
                <td><span class="glyphicon glyphicon-remove" style="cursor:pointer;" ng-confirm-click="Deletar Pokemon?" confirmed-click="deletePokemon(pokemon);"></span></td>
            </tr>
        </tbody>
    </table>
</div>

src/PokemonGOWeb/Views/Pokemon/Update.cshtml
@{
    ViewBag.Title = "Editar Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Pokémon</h2>

<form>
    <div class="form-group">
        <img src="http://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png" class="img-rounded">
    </div>
    <div class="form-group">
        <label>Alterar o nome</label>
        <input type="text" class="form-control" value="Pikachu">
    </div>
    <div class="form-group">
        <label for="exampleInputFile">Defina uma nova imagem</label>
        <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
        <small id="fileHelp" class="form-text text-muted">Insira a imagem do Pokémon, porém não poderá ser maior que 4 MB.</small>
    </div>
    <fieldset class="form-group">
        <label>Já possuo o Pokémon?</label>
        <div class="form-check">
            <label class="form-check-label">
                <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                Sim
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input type="radio" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                Não
            </label>
        </div>
    </fieldset>
    <div class="form-group">
        <label for="exampleSelect1">Tipo de Pokémon</label>
        <select class="form-control" id="exampleSelect1">
            <option selected>Elétrico</option>
            <option>Grama</option>
            <option>Fogo</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

src/PokemonGOWeb/Views/PokemonType/Create.cshtml
@{
    ViewBag.Title = "Criar Tipo de Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar novo tipo de Pokémon</h2>

<form>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Insira uma nova descrição">
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

src/PokemonGOWeb/Views/PokemonType/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

src/PokemonGOWeb/Views/PokemonType/Index.cshtml
@{
    ViewBag.Title = "Tipos de Pokémon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tipos de Pokemon</h2>

<form class="form-inline">
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Create", "PokemonType")'">Criar novo tipo de Pokémon</button>
    <div class="form-group">
        <input type="text" class="form-control">
    </div>
    <button type="submit" class="btn btn-default">Buscar</button>
</form>
<table class="table table-striped" style="width:50%">
    <thead>
        <tr>
            <th>#</th>
            <th>Description</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Elétrico</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Grama</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Fogo</td>
            <td><span class="glyphicon glyphicon-pencil" onclick="location.href='@Url.Action("Update", "PokemonType")'" style="cursor:pointer;"></span></td>
            <td><span class="glyphicon glyphicon-remove" onclick="location.href='@Url.Action("Delete", "PokemonType")'" style="cursor:pointer;"></span></td>
        </tr>
    </tbody>
</table>

src/PokemonGOWeb/Views/PokemonType/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>

src/PokemonGOWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POD Moss Applications</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="pokecit">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pokémon GO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pokémon", "Index", "Pokemon")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <img src="http://www.corpbusiness.com.br/_img/conteudo/noticia/13108/080514_102541.jpg" style="width:30px;" /></p>
        </footer>
    </div>
    @*Add AngularJs reference*@
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*Add App JS file*@
    <script src="~/Scripts/pokecitApp.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>